### ISSUE TITLE
.NET Core version tries to load System.Management.WmiNetUtilsHelper

### ISSUE THREAD

**Issue by HengYeDev** [perpetualKid/ORTS-MG#43]
When I use the netcoreapp3.1 version which should not depend on the full .NET, there is this error when .NET full isn't installed:

```
Error: System.TypeInitializationException: The type initializer for 'System.Management.ManagementPath' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (126): Failed to load required native library 'C:\windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.
   at System.Management.WmiNetUtilsHelper..cctor()
   --- End of inner exception stack trace ---
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type type)
   at System.Management.ManagementPath.CreateWbemPath(String path)
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.ManagementPath..cctor()
   --- End of inner exception stack trace ---
   at System.Management.ManagementPath.get_DefaultPath()
   at System.Management.ManagementScope._Clone(ManagementScope scope, IdentifierChangedEventHandler handler)
   at System.Management.ManagementScope._Clone(ManagementScope scope)
   at System.Management.ManagementObjectSearcher..ctor(ManagementScope scope, ObjectQuery query, EnumerationOptions options)
   at System.Management.ManagementObjectSearcher..ctor(String queryString)
   at Orts.Common.Info.SystemInfo.WriteEnvironment(StringBuilder output)
   at Orts.Common.Info.SystemInfo.WriteSystemDetails()
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.InitLogging(Boolean appendLog)
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.<>c__DisplayClass27_0.<Load>b__0()
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Load()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.Load()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.DoLoad()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.LoaderThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


Information: Game.PopState()  
```
`System.Management is only available in the full version (https://stackoverflow.com/questions/54815319/net-core-managementobjectsearcher-throws-exception-on-initializing)

**Comment by HengYeDev** [comment]
it seems that this library is used in the following files:
`[heng@heng-arch-xps ORTS-MG]$ grep -r System.Management
Source/ActivityRunner/Viewer3D/Viewer.cs:using System.Management;
Source/Orts.Common/Info/SystemInfo.cs:using System.Management;
Source/Orts.Common/Orts.Common.csproj:    <PackageReference Include="System.Management" Version="5.0.0" />
`

**Comment by HengYeDev** [comment]
btw I'm running ORTS-MG on arch linux with wine

**Comment by perpetualKid** [comment]
I think this error doesn't surface on Windows OS since .NET 4.8 is installed by default on fully patched OS (Win10, Win7SP1), as I've never seen this before as Windows user even on brand new machine. 

I think there is no real use of any System.Management functionality beside of some Hardware/OS info when initializing the log, will need to check if there is some replacement to work without .NET dependency. Maybe you could try to disable "Logging", does it make a difference?

Independently, would be interested to learn more about your experience running ORTS-MG on non-Windows!

**Comment by HengYeDev** [comment]
I got regular Open Rails testing version to work with Wine 5.11 instead of 6.2 as regressions were introduced, which means that .NET works in those versions. Haven't gotten around to testing MG on that though.

**Comment by perpetualKid** [comment]
I've added a try/catch, should be available in newest build, can you test?

**Comment by HengYeDev** [comment]
Sure. Where's the exe's to test

**Comment by perpetualKid** [comment]
that was still in the Build, available now as #1.3.6-ci.10 in the ci channel. You may need to restart the app, and check if Options->Update Frequency is set to check for every start.

**Comment by perpetualKid** [comment]
is that working now? @HengYeDev

**Comment by HengYeDev** [comment]
I'm real busy these days...give me a week please. btw regular edition works perfectly on wine


Heng Ye
https://yeheng.org | Twitter https://twitter.com/HengYeDev







---- On Sat, 27 Feb 2021 04:16:49 -0500 perpetualKid <notifications@github.com> wrote ----




is that working now? https://github.com/HengYeDev

**Comment by HengYeDev** [comment]
Can i reopen this? I tried today and it's still broken

**Comment by HengYeDev** [comment]
(but with a different error! progress!)

**Comment by HengYeDev** [comment]
it even happens if logging is OFF

**Comment by HengYeDev** [comment]
`Error: System.PlatformNotSupportedException: Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
   at System.Management.WmiNetUtilsHelper.<>c__DisplayClass104_0.<LoadPlatformNotSupportedDelegates>b__39(Int32 _, IntPtr __, APTTYPE& ___)
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type type)
   at System.Management.ManagementPath.CreateWbemPath(String path)
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.ManagementClass..ctor(String path)
   at Orts.ActivityRunner.Viewer3D.Viewer.UpdateAdapterInformation(GraphicsAdapter graphicsAdapter)
   at Orts.ActivityRunner.Viewer3D.Viewer.Initialize()
   at Orts.ActivityRunner.Viewer3D.Viewer..ctor(Simulator simulator, Game game)
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Start(UserSettings settings)
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.<>c__DisplayClass27_0.<Load>b__0()
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Load()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.Load()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.DoLoad()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.LoaderThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


`

**Comment by HengYeDev** [comment]
btw, @perpetualKid feel free to keep closed if you're not that interested into getting it to work on linux...if you want to i would recommend setting up a virtual machine to test

**Comment by HengYeDev** [comment]
hmm. it's probably not that you didn't fix it - probably because the updater is broken and its telling me its updated when its not

**Comment by HengYeDev** [comment]
I might be able to fix it by installing .NET 4.0 (regular version) but i don't want to do that, since it's supposed to be .NET Core only

**Comment by HengYeDev** [comment]
I installed .net4 into the wine prefix and it is still broken so i don't think it's all because the lack of .net

**Comment by perpetualKid** [comment]
> `Error: System.PlatformNotSupportedException: Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
> at System.Management.WmiNetUtilsHelper.<>c__DisplayClass104_0.b__39(Int32 _, IntPtr __, APTTYPE& ___)
> at System.Management.MTAHelper.IsNoContextMTA()
> at System.Management.MTAHelper.CreateInMTA(Type type)
> at System.Management.ManagementPath.CreateWbemPath(String path)
> at System.Management.ManagementPath..ctor(String path)
> at System.Management.ManagementClass..ctor(String path)
> at Orts.ActivityRunner.Viewer3D.Viewer.UpdateAdapterInformation(GraphicsAdapter graphicsAdapter)
> at Orts.ActivityRunner.Viewer3D.Viewer.Initialize()
> at Orts.ActivityRunner.Viewer3D.Viewer..ctor(Simulator simulator, Game game)
> at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Start(UserSettings settings)
> at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.<>c__DisplayClass27_0.b__0()
> at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Load()
> at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.Load()
> at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.DoLoad()
> at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.LoaderThread()
> at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> at System.Threading.ThreadHelper.ThreadStart()
> 
> `
@HengYeDev 
this is a differnt place in the code than the first one, I just discovered that myself a few days back only but haven't started looking into it.
I've moved that to a new issue #51 but keep this one closed.

Any contributions regardless platform are welcome but given limited resources, focus currently is on Windows primarily. Even when moving to .NET Core, there are quite a bunch of dependencies to Windows which would need to be resolved to make OR run natively on non-Windows platforms, and that is not currently possible to cover given resource constraint. 
So for the time being it seems using the .NET Framework version is better suited for Linux, and that is still available.

The updater has some issue resolving version numbers which is noticed and work in progress.
