### ISSUE TITLE
`Error: System.PlatformNotSupportedException: Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.

### ISSUE THREAD

**Issue by perpetualKid** [perpetualKid/ORTS-MG#51]
`Error: System.PlatformNotSupportedException: Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
   at System.Management.WmiNetUtilsHelper.<>c__DisplayClass104_0.<LoadPlatformNotSupportedDelegates>b__39(Int32 _, IntPtr __, APTTYPE& ___)
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type type)
   at System.Management.ManagementPath.CreateWbemPath(String path)
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.ManagementClass..ctor(String path)
   at Orts.ActivityRunner.Viewer3D.Viewer.UpdateAdapterInformation(GraphicsAdapter graphicsAdapter)
   at Orts.ActivityRunner.Viewer3D.Viewer.Initialize()
   at Orts.ActivityRunner.Viewer3D.Viewer..ctor(Simulator simulator, Game game)
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Start(UserSettings settings)
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.<>c__DisplayClass27_0.<Load>b__0()
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Load()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.Load()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.DoLoad()
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.LoaderThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

`

_Originally posted by @HengYeDev in https://github.com/perpetualKid/ORTS-MG/issues/43#issuecomment-805111043_

**Comment by HengYeDev** [comment]
For the record:
* Same effect with logging turned on or off
* Does not happen when .net is installed

**Comment by perpetualKid** [comment]
maybe using a package like this https://github.com/Jinjinov/Hardware.Info to suppport more native OS functionality

**Comment by HengYeDev** [comment]
No longer an error, its just logged. Close?
